name: RfnetAPI
version: ${project.version}
main: com.reflectednetwork.rfnetapi.RfnetAPI
load: STARTUP
softdepend:
  - SlimeWorldManager
api-version: 1.16
libraries:
  - io.lettuce:lettuce-core:6.1.1.RELEASE
  - org.mongodb:mongodb-driver-sync:4.2.3
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21