name: RfnetAPI
version: ${project.version}
main: com.reflectednetwork.rfnetapi.RfnetAPI
load: STARTUP
softdepend:
  - SlimeWorldManager
api-version: 1.17
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.30